version: '3'
services:
  server:
    environment:
      # slackbot auth
      - BOT_TOKEN
      - VERIFICATION
      - SUPER_TOKEN
      # postgres connection
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    build:
      context: .
      args:
       - "timezone=Europe/Prague"
    image: "kiwicom/iwantbot"
    volumes:
     - .:/app
    ports:
     - "8080:80"

  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    environment:
      TZ: "Europe/Prague"

  worker:
    build:
      context: .
    command: celery -A bot_worker worker --loglevel=info --beat --autoscale=20,0
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
 
  postgres:
    image: "postgres:9.6-alpine"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER